version: "3.8"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/index
      - ./app:/node_modules
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/index
      - ./app:/node_modules
    stdin_open: true
    tty: true
